int random = 0;
int count = 0;
int xPos = 0;
int yPos = 0;
int input = 0;
char[] board = new char[9];
int i = 0;
boolean full = true;
boolean over = false;
private static final char AI = 'a';
private static final char HUMAN = 'h';
char winner;
